"""Build myFont tier charsets + generated JS (all ASCII-safe via \\u escapes)."""
import base64
import json
import unicodedata

from fontTools.ttLib import TTFont

REPO = 'C:/Users/andre/Documents/GitHub/myFont'
cmap = TTFont(REPO + '/vendor/fonts/DejaVuSans.ttf').getBestCmap()

MINIMAL = ('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
           + ".,;:!?'-()@#&+/$\"")
SPANISH_EXTRA = [0xD1, 0xF1, 0xC1, 0xC9, 0xCD, 0xD3, 0xDA,
                 0xE1, 0xE9, 0xED, 0xF3, 0xFA, 0xFC, 0xBF, 0xA1]
SPANISH = MINIMAL + ''.join(chr(c) for c in SPANISH_EXTRA)
SPANISH_NEW = ''.join(chr(c) for c in SPANISH_EXTRA)
have = set(SPANISH)

# latin1: printable Latin-1 Supplement minus invisibles and what we have
latin1 = [c for c in range(0xA0, 0x100)
          if c not in (0xA0, 0xAD) and chr(c) not in have]
# exta: assigned Latin Extended-A only
exta = []
for c in range(0x100, 0x180):
    try:
        unicodedata.name(chr(c))
    except ValueError:
        continue
    if chr(c) not in have:
        exta.append(c)
# pro: punctuation/currency beyond the above
pro = [0x2013, 0x2014, 0x2018, 0x2019, 0x201A, 0x201C, 0x201D, 0x201E,
       0x2020, 0x2021, 0x2022, 0x2026, 0x2039, 0x203A,
       0x20AC, 0x2122, 0x2116]
pro = [c for c in pro if chr(c) not in have]

TIERS = {'minimal': MINIMAL, 'spanish': SPANISH_NEW,
         'latin1': ''.join(chr(c) for c in latin1),
         'exta': ''.join(chr(c) for c in exta),
         'pro': ''.join(chr(c) for c in pro)}

# coverage gate: every tier char must exist in DejaVu
cum = ''
for name, s in TIERS.items():
    missing = [hex(ord(c)) for c in s if ord(c) not in cmap]
    assert not missing, f'{name} missing in DejaVu: {missing}'
    cum += s
    print(f'{name}: tier={len(s)} total={len(cum)} pages={-(-len(cum) // 42)}')


def esc(s):
    out = []
    for c in s:
        o = ord(c)
        out.append(c if 32 <= o < 127 and c not in '"\\' else '\\u%04x' % o)
    return ''.join(out)


# charsets-generated.js
js = ('/* AUTO-GENERATED by scripts/build-tiers.py — do not edit by hand. */\n'
      'window.MYFONT_CHARSETS = {\n')
for name, s in TIERS.items():
    js += f'  {name}: "{esc(s)}",\n'
js += '};\n'
open(REPO + '/charsets-generated.js', 'w', encoding='utf-8', newline='').write(js)

# dejavu-b64.js (file:// + offline fallback)
raw = open(REPO + '/vendor/fonts/DejaVuSans.ttf', 'rb').read()
b64 = base64.b64encode(raw).decode('ascii')
open(REPO + '/dejavu-b64.js', 'w', encoding='utf-8', newline='').write(
    '/* AUTO-GENERATED by scripts/build-tiers.py — DejaVu Sans 2.37 base64. */\n'
    'window.MYFONT_DEJAVU_B64 = "' + b64 + '";\n')
print('charsets-generated.js + dejavu-b64.js ok, ttf bytes:', len(raw))

# i18n additions (ASCII-safe)
I18N_ADD = {
    'charsetLatin1': ('Latino (\\u00a9\\u00ae\\u20ac\\u00ab\\u00bb\\u00df\\u00e6\\u2026)',
                      'Latin (\\u00a9\\u00ae\\u20ac\\u00ab\\u00bb\\u00df\\u00e6\\u2026)'),
    'charsetExtA': ('Europeo central (\\u010d\\u0161\\u017e\\u2026)',
                    'Central European (\\u010d\\u0161\\u017e\\u2026)'),
    'charsetPro': ('Signos pro (\\u2013\\u2014\\u2018\\u2019\\u201c\\u201d\\u2022\\u2026\\u20ac)',
                   'Pro punctuation (\\u2013\\u2014\\u2018\\u2019\\u201c\\u201d\\u2022\\u2026\\u20ac)'),
}
for lang, idx in (('es', 0), ('en', 1)):
    p = f'{REPO}/i18n/{lang}.json'
    d = json.load(open(p, encoding='utf-8'))
    for k, (es_v, en_v) in I18N_ADD.items():
        d[k] = es_v if idx == 0 else en_v
    open(p, 'w', encoding='utf-8', newline='').write(
        json.dumps(d, ensure_ascii=False, indent=2) + '\n')
print('i18n tiers added')
