"""Build myFont tier charsets + generated JS (all ASCII-safe via \\u escapes)."""
import base64
import json
import unicodedata

from fontTools.ttLib import TTFont

REPO = 'C:/Users/andre/Documents/GitHub/myFont'
cmap = TTFont(REPO + '/vendor/fonts/DejaVuSans.ttf').getBestCmap()

MINIMAL = ('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
           + ".,;:!?'-()@#&+/$\"")
SPANISH_EXTRA = [0xD1, 0xF1, 0xC1, 0xC9, 0xCD, 0xD3, 0xDA,
                 0xE1, 0xE9, 0xED, 0xF3, 0xFA, 0xFC, 0xBF, 0xA1]
SPANISH = MINIMAL + ''.join(chr(c) for c in SPANISH_EXTRA)
SPANISH_NEW = ''.join(chr(c) for c in SPANISH_EXTRA)
have = set(SPANISH)

# latin1: printable Latin-1 Supplement minus invisibles and what we have
latin1 = [c for c in range(0xA0, 0x100)
          if c not in (0xA0, 0xAD) and chr(c) not in have]
# exta: assigned Latin Extended-A only
exta = []
for c in range(0x100, 0x180):
    try:
        unicodedata.name(chr(c))
    except ValueError:
        continue
    if chr(c) not in have:
        exta.append(c)
# pro: punctuation/currency beyond the above
pro = [0x2013, 0x2014, 0x2018, 0x2019, 0x201A, 0x201C, 0x201D, 0x201E,
       0x2020, 0x2021, 0x2022, 0x2026, 0x2039, 0x203A,
       0x20AC, 0x2122, 0x2116]
pro = [c for c in pro if chr(c) not in have]

TIERS = {'minimal': MINIMAL, 'spanish': SPANISH_NEW,
         'latin1': ''.join(chr(c) for c in latin1),
         'exta': ''.join(chr(c) for c in exta),
         'pro': ''.join(chr(c) for c in pro)}


def covered(s):
    """Keep only chars DejaVu can render (ghost must exist for every cell)."""
    return ''.join(c for c in dict.fromkeys(s) if ord(c) in cmap)


# Independent groups for the custom picker (self-contained: each works alone).
GROUPS = {
    'kbd': covered('*<=>[]\\^_`{|}~'),
    'math': covered('=≠≈≤≥≡∝∞∅√∛∀∃∄∈∉∋∪∩⊂⊃⊆⊇⊕⊗⊥∥∴∵∠→←↔⇒⇔∧∨¬×÷∑∏∫∬∂∇∆π'),
    'greek': covered('αβγδεζηθικλμνξοπρσςτυφχψω'
                     'ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ'),
    'sub': covered('₀₁₂₃₄₅₆₇₈₉⁰¹²³⁴⁵⁶⁷⁸⁹ⁿ'),
    'arrows': covered('↑↓↕←→↔↖↗↘↙↚↛↜↝↞↟↠↡↢↣↤↥↦↧↨↩↪↫↬↭↮↯'
                      '↰↱⇐⇑⇒⇓⇔⇍⇎⇏⇠⇡⇢⇣⏎↵↺↻⇄⇅⇋⇌'),
    'curr': covered('$¢£¤¥€₹₺₦₫₴₡₵₲₮₩₪฿₿₽₸'),
    'shapes': covered('■□▣▲▼△▽●○◆◇★☆✓✗✔✘⚠'),
    'music': covered('♩♪♫♬♭♯♮'),
}
# cyrillic: every assigned, DejaVu-covered Cyrillic code point
cyr = []
for c in range(0x400, 0x530):
    try:
        name = unicodedata.name(chr(c))
    except ValueError:
        continue
    if name.startswith('CYRILLIC') and c in cmap:
        cyr.append(c)
GROUPS['cyr'] = ''.join(chr(c) for c in cyr)

# coverage gate: every tier char must exist in DejaVu
cum = ''
for name, s in TIERS.items():
    missing = [hex(ord(c)) for c in s if ord(c) not in cmap]
    assert not missing, f'{name} missing in DejaVu: {missing}'
    cum += s
    print(f'{name}: tier={len(s)} total={len(cum)} pages={-(-len(cum) // 42)}')

# gate for custom groups too
for name, s in GROUPS.items():
    assert s, f'group {name} empty after coverage filter'
    missing = [hex(ord(c)) for c in s if ord(c) not in cmap]
    assert not missing, f'group {name} missing in DejaVu: {missing}'
    print(f'group {name}: {len(s)} chars')


def esc(s):
    out = []
    for c in s:
        o = ord(c)
        out.append(c if 32 <= o < 127 and c not in '"\\' else '\\u%04x' % o)
    return ''.join(out)


# charsets-generated.js (tiers + custom groups)
js = ('/* AUTO-GENERATED by scripts/build-tiers.py — do not edit by hand. */\n'
      'window.MYFONT_CHARSETS = {\n')
for name, s in {**TIERS, **GROUPS}.items():
    js += f'  {name}: "{esc(s)}",\n'
js += '};\n'
open(REPO + '/charsets-generated.js', 'w', encoding='utf-8', newline='').write(js)

# dejavu-b64.js (file:// + offline fallback)
raw = open(REPO + '/vendor/fonts/DejaVuSans.ttf', 'rb').read()
b64 = base64.b64encode(raw).decode('ascii')
open(REPO + '/dejavu-b64.js', 'w', encoding='utf-8', newline='').write(
    '/* AUTO-GENERATED by scripts/build-tiers.py — DejaVu Sans 2.37 base64. */\n'
    'window.MYFONT_DEJAVU_B64 = "' + b64 + '";\n')
print('charsets-generated.js + dejavu-b64.js ok, ttf bytes:', len(raw))

# i18n additions.
# NOTA: usar caracteres REALES, no escapes '\\uXXXX' — un backslash literal en el
# JSON se muestra crudo en la UI (bug preexistente en charsetLatin1/ExtA/Pro).
# gen-embedded.py se encarga del ASCII-safe para file://.
I18N_ADD = {
    'charsetLatin1': ('Latino (©®€«»ßæ…)',
                      'Latin (©®€«»ßæ…)'),
    'charsetExtA': ('Europeo central (čšž…)',
                    'Central European (čšž…)'),
    'charsetPro': ('Signos pro (–—‘’“”•…€)',
                   'Pro punctuation (–—‘’“”•…€)'),
    'charsetCustom': ('Personalizado (elige tus símbolos)',
                      'Custom (pick your symbols)'),
    'pickerTitle': ('Grupos: marca los que quieras (puedes combinarlos)',
                    'Groups: check the ones you want (mix and match)'),
    'grpKbd': ('Símbolos de teclado', 'Keyboard symbols'),
    'grpMath': ('Matemáticos / álgebra', 'Math / algebra'),
    'grpGreek': ('Letras griegas', 'Greek letters'),
    'grpSub': ('Subíndices y superíndices', 'Subscripts & superscripts'),
    'grpArrows': ('Flechas', 'Arrows'),
    'grpCurr': ('Monedas', 'Currencies'),
    'grpShapes': ('Formas y útiles (✓ ✗ ★)', 'Shapes & marks (✓ ✗ ★)'),
    'grpMusic': ('Música', 'Music'),
    'grpCyr': ('Cirílico', 'Cyrillic'),
    'freeLabel': ('O escribe / pega caracteres sueltos',
                  'Or type / paste individual characters'),
    'freePh': ('ej.: α β ∞ ≡ ...',
               'e.g.: α β ∞ ≡ ...'),
    'pickSome': ('Elige al menos un grupo o escribe caracteres.',
                 'Pick at least one group or type some characters.'),
    'warnNoCover': ('{n} sin glifo en la fuente, omitidos: {list}',
                    '{n} not in the font, skipped: {list}'),
}
for lang, idx in (('es', 0), ('en', 1)):
    p = f'{REPO}/i18n/{lang}.json'
    d = json.load(open(p, encoding='utf-8'))
    for k, (es_v, en_v) in I18N_ADD.items():
        d[k] = es_v if idx == 0 else en_v
    open(p, 'w', encoding='utf-8', newline='').write(
        json.dumps(d, ensure_ascii=False, indent=2) + '\n')
print('i18n tiers added')
