"""Generate i18n-embedded.js from es/en.json (pure ASCII, safe for file:// fallback)."""
import json

REPO = 'C:/Users/andre/Documents/GitHub/myFont'
es = json.load(open(REPO + '/i18n/es.json', encoding='utf-8'))
en = json.load(open(REPO + '/i18n/en.json', encoding='utf-8'))
assert set(es) == set(en), 'key mismatch'
blob = json.dumps({'es': es, 'en': en}, ensure_ascii=True, indent=2)
out = ('/* AUTO-GENERATED by scripts/gen-embedded.py — do not edit by hand. */\n'
       'window.MYFONT_I18N = ' + blob + ';\n')
open(REPO + '/i18n-embedded.js', 'w', encoding='utf-8', newline='').write(out)
print('i18n-embedded.js ok, keys:', len(es))
